name: aesd-ci

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        clean: true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential gcc-multilib

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Run make
      run: make

